## Creating Numpy Arrays

In [1]:
!pip install numpy -- upgrade

  Could not find a version that satisfies the requirement upgrade (from versions: )
No matching distribution found for upgrade


In [2]:
 import numpy as np

#### 1. Create an array with python list or tuple using array function

In [3]:
a = [2,4,6,8,10]
a

[2, 4, 6, 8, 10]

In [4]:
type(a)

list

In [5]:
array_1 = np.array(a)
array_1

array([ 2,  4,  6,  8, 10])

In [6]:
type(array_1)

numpy.ndarray

#### This is an one dimensional array

In [7]:
array_1.size

5

In [8]:
 b = [[2,4,6,8],[3,6,9,12]]

In [9]:
array_2 = np.array(b)
array_2

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

#### This is a two dimensional array.

In [10]:
array_2.size

8

In [11]:
array_2.shape

(2, 4)

#### 2. Create an array with an arange function

<b>arange</b> : Like the built-in range but returns an ndarray instead of a list.

In [12]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [13]:
np.arange(2,6)

array([2, 3, 4, 5])

In [14]:
np.arange(3,20,4)

array([ 3,  7, 11, 15, 19])

#### Using reshape to create n dimensional arrays

In [15]:
np.arange(8).reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

for arange ( 8 ), the possible combinations for reshape are (2,4), (4,2), (1,8)

In [16]:
np.arange(8).reshape(1,8)

array([[0, 1, 2, 3, 4, 5, 6, 7]])

#### It also accepts float arguments

In [17]:
array_of_floats = np.arange( 0, 5, 0.2)
array_of_floats

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

#### 3. Create an array with an linespace function

In [18]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

When arange ( ) is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace ( ) that receives as an argument the number of elements that we want, instead of the step.

#### 4. Create an array with zeros,ones,empty and eye function

<b>zeros, zeros_like</b> : Like ones and ones_like but producing arrays of 0’s instead

In [19]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

<b> ones, ones_like </b> : Produce an array of all 1’s with the given shape and dtype. ones_like takes another array and produces a ones array of the same shape and dtype.

In [20]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.ones( ( 3,5,6 ) )

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

#### Here three dimensional 5*6 (maticices) arrays has been created.

In [22]:
np.empty((3,4))

array([[0.00000000e+000, 1.49457587e-154, 3.45845952e-323,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

####  np.eye() creates an identity matrix. eye, identity : Create a square N x N identity matrix (1’s on the diagonal and 0’s elsewhere

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

  #### 5. Create an array with random.rand function

In [24]:
np.random.rand(3,1)

array([[0.22001789],
       [0.72552284],
       [0.55642481]])

In [25]:
np.floor(10*np.random.rand(2,4))

array([[7., 9., 9., 9.],
       [9., 5., 8., 7.]])